# Create a Jekyll container for GitHub Pages
# See this for current supported versions: https://pages.github.com/versions/
FROM docker.io/ruby:3.3

# Update the Ruby bundler
RUN gem update bundler 

# Install Jekyll
RUN gem install bundler jekyll 