name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'viewpoints/**.md'
      - 'diagrams/**'
      - '**.md'
      - '**.yml'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: viewpoints
          output_dir: pdfs/
          images_dir: diagrams
          image_import: ../diagrams
          # Default is true, can set to false to only get PDF files
          build_html: false
      - name: Show files changed
        run: pwd; ls -la pdfs
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '*.pdf'
