name: Publish Main
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - .github/workflows/publish-main.yml
      - .github/workflows/deploy-docs.yml
      - .github/workflows/build-docs/**

permissions:
  contents: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-docs.yml
