name: Publish Docs
on:
  push:
    branches:
      - TdSE2024
      - TdSE2023
      - Initial-Release

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-docs.yml
    with:
      target-folder: version/${{ github.ref_name }}
